config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)
  devise_for :users, ActiveAdmin::Devise.config
  devise_for :admin_users, ActiveAdmin::Devise.config
  
  post 'login' => 'sessions#create'

  delete 'logout' => 'sessions#destroy'

  get 'login' => 'sessions#new'

  post 'login_success' => 'students#show'
  
  post 'search_course' => 'students#searchCourse'
  
  get 'search_course' => 'students#show'
  
  resources :students
  resources :feilds
  resources :departments
  resources :courses
  
  root 'sessions#new'

end

app/models/feild.rb
class Feild < ActiveRecord::Base
   
    belongs_to :department
    has_many :courses
end

app/controllers/feilds_controller.rb
class FeildsController < ApplicationController
  before_action :set_feild, only: [:show, :edit, :update, :destroy]

  # GET /feilds
  # GET /feilds.json
  def index
    @feilds = Feild.all
  end

  # GET /feilds/1
  # GET /feilds/1.json
  def show
  end

  # GET /feilds/new
  def new
    @feild = Feild.new
  end

  # GET /feilds/1/edit
  def edit
  end

  # POST /feilds
  # POST /feilds.json
  def create
    @feild = Feild.new(feild_params)

    respond_to do |format|
      if @feild.save
        format.html { redirect_to @feild, notice: 'Feild was successfully created.' }
        format.json { render :show, status: :created, location: @feild }
      else
        format.html { render :new }
        format.json { render json: @feild.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /feilds/1
  # PATCH/PUT /feilds/1.json
  def update
    respond_to do |format|
      if @feild.update(feild_params)
        format.html { redirect_to @feild, notice: 'Feild was successfully updated.' }
        format.json { render :show, status: :ok, location: @feild }
      else
        format.html { render :edit }
        format.json { render json: @feild.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feilds/1
  # DELETE /feilds/1.json
  def destroy
    @feild.destroy
    respond_to do |format|
      format.html { redirect_to feilds_url, notice: 'Feild was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_feild
      @feild = Feild.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def feild_params
      params.require(:feild).permit(:feildName,:departmentId)
    end
end

app/helpers/feilds_helper.rb
module FeildsHelper
end

app/views/feilds/_form.html.erb
<%= form_for(@feild) do |f| %>
  <% if @feild.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@feild.errors.count, "error") %> prohibited this feild from being saved:</h2>

      <ul>
      <% @feild.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :feildId %><br>
    <%= f.number_field :id %>
  </div>
  <div class="field">
    <%= f.label :feildName %><br>
    <%= f.text_field :feildName %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/feilds/edit.html.erb
<h1>Editing Feild</h1>

<%= render 'form' %>

<%= link_to 'Show', @feild %> |
<%= link_to 'Back', feilds_path %>

app/views/feilds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Feilds</h1>

<table>
  <thead>
    <tr>
      <th>Feildid</th>
      <th>Feildname</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @feilds.each do |feild| %>
      <tr>
        <td><%= feild.id %></td>
        <td><%= feild.feildName %></td>
        <td><%= link_to 'Show', feild %></td>
        <td><%= link_to 'Edit', edit_feild_path(feild) %></td>
        <td><%= link_to 'Destroy', feild, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Feild', new_feild_path %>

app/views/feilds/new.html.erb
<h1>New Feild</h1>

<%= render 'form' %>

<%= link_to 'Back', feilds_path %>

app/views/feilds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Feildid:</strong>
  <%= @feild.id %>
</p>

<p>
  <strong>Feildname:</strong>
  <%= @feild.feildName %>
</p>

<%= link_to 'Edit', edit_feild_path(@feild) %> |
<%= link_to 'Back', feilds_path %>