config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)
  devise_for :users, ActiveAdmin::Devise.config
  devise_for :admin_users, ActiveAdmin::Devise.config
  
  post 'login' => 'sessions#create'

  delete 'logout' => 'sessions#destroy'

  get 'login' => 'sessions#new'

  post 'login_success' => 'students#show'
  
  post 'search_course' => 'students#searchCourse'
  
  get 'search_course' => 'students#show'
  
  resources :students
  resources :feilds
  resources :departments
  resources :courses
  
  root 'sessions#new'

end

app/models/student.rb
class Student < ActiveRecord::Base
    
    #before_save {self.emailId = :emailId.downcase}
    
    
    validates :firstName, presence: true, length: {maximum: 50}
    validates :lastName, presence: true, length: {maximum: 50}
    #VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+z/i
    #validates :emailId, presence: true, length: {maximum: 50}, format:{with:VALID_EMAIL_REGEX},
    #    uniqueness:{case_sensitive: false}
    has_secure_password
    validates :password, presence: true, length: {minimum: 6}
    
    has_many :microposts
    
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  #before_action :set_student, only: [:show, :edit, :update, :destroy]
  respond_to :json
  # GET /students
  # GET /students.json
  def index
    
    @students = Student.all
    #respond_to do |format|
    #  format.html #index.html.erb
    #  format.json {render json: @students}
    #end
    respond_with @students
    
  end

  # GET /students/1
  # GET /students/1.json
  def show
     @student = Student.find(params[:id])
     if !params[:id].nil?
       #@student = Student.find(params[:id])
       session[:studentId] = @student.id
       
     else 
       @student = Student.find(session[:studentId]);
     end
     #byebug
     
     @microposts = Micropost.where(student_id: params[:id]).all
     @courses ||= Array.new
     @microposts.each do |m|
       @course = Course.find(m.course_id)
       @courses.push(@course)
     end
     @courseSearched = session[:courseSearched]
     @feildOfCourse = session[:feildOfSearchedCourse]
     #session[:courseSearched] = nil
     #byebug
    
  end

  # GET /students/new
  def new
    @student = Student.new
    
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def addCourse
    
  end
  
  def searchCourse
    
    @courseSearched = Course.where("courseDescription like?","%#{params[:content]}%")
    session[:courseSearched] = @courseSearched.first.courseDescription
    @feild = Feild.find(@courseSearched.first.feildId);
    session[:feildOfSearchedCourse] = @feild.feildName
    @student = Student.find(session[:studentId]);
    #byebug
    respond_to do |format|
      format.html { redirect_to @student}
      format.json { render :show, status: :ok, location: @student }
    end
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      #byebug
      @student = Student.find(session[:studentId])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      #params.require(:student).permit(:firstName, :lastName, :emailId, :emergencyContact, :mailingAddress)
      #params.require(:student).permit(:firstName, :lastName, :emailId, :mailingAddress, 
      #:emergencyContact, :password_digest, :middleName, :mobileNo, :)
      params.require(:student).permit!
    end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
<%= form_for(@student) do |f| %>
  <% if @student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% @student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  
  <div class="field">
    <%= f.label :firstName %><br>
    <%= f.text_field :firstName %>
  </div>
  <div class="field">
    <%= f.label :middleName %><br>
    <%= f.text_field :middleName %>
  </div>
  <div class="field">
    <%= f.label :lastName %><br>
    <%= f.text_field :lastName %>
  </div>
  <div class="field">
    <%= f.label :emailId %><br>
    <%= f.text_field :emailId %>
  </div>
  <div class="field">
    <%= f.label :mobileNo %><br>
    <%= f.text_field :mobileNo %>
  </div>
  <div class="field">
    <%= f.label :permanentAddress %><br>
    <%= f.text_field :permanentAddress %>
  </div>
  <div class="field">
    <%= f.label :mailingAddress %><br>
    <%= f.text_field :mailingAddress %>
  </div>
  <div class="field">
    <%= f.label :emergencyContact %><br>
    <%= f.text_field :emergencyContact %>
  </div>
  <div>
  <%= f.label :password %>
      <%= f.password_field :password %>
  </div>
  <div>
      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/students/_search_course.html.erb
<%= form_tag('/search_course') do -%>
<table>
    <tr>
        <td>
        <div class="field">
            <%= search_field_tag 'content', 'Search course by Description' %>
        </div>
        <div><%= submit_tag 'Search' %></div> 
            
        </td>
        
    </tr>
    <tr>
      <% if session[:courseSearched] %>
      
        <table>
          
          <tr>
              <td>You searched for </td>
            <td><%= session[:courseSearched] %> </td>
            <td><%= session[:feildOfSearchedCourse] %></td>
          </tr>
          
        </table>
      <% end %>
    
    </tr>
    
</table>

<% end -%>

app/views/students/edit.html.erb
<h1>Editing Student</h1>

<%= render 'form' %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/new.html.erb
<h1>New Student</h1>

<%= render 'form' %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<table class="table table-striped">
  <tr>
    <td>
      <p>
  <strong>First Name:</strong>
  <%= @student.firstName %>
</p>

<p>
  <strong>Middle Name:</strong>
  <%= @student.middleName %>
</p>

<p>
  <strong>Last Name:</strong>
  <%= @student.lastName %>
</p>

<p>
  <strong>Email Id:</strong>
  <%= @student.emailId %>
</p>

<p>
  <strong>Mobile No:</strong>
  <%= @student.mobileNo %>
</p>

<!-- Commented
<p>
  <strong>Permanent Address:</strong>
  <%= @student.permanentAddress %>
</p>

<p>
  <strong>Mailing Address:</strong>
  <%= @student.mailingAddress %>
</p>
<p>
  <strong>Password:</strong>
  <%= @student.password %>
</p>
<p>
  <strong>Password Confirmation:</strong>
  <%= @student.password_confirmation %>
</p>
<p>
  <strong>Department Id:</strong>
  <%= @student.departmentId %>
</p>
-->
<ol class="courses">
  <%= render @courses %>
</ol>
<%= link_to 'Edit', edit_student_path(@student) %>
      
      
    </td>
    <td>
      <section class="search_course">
        <%= render 'search_course' %>
      </section>
      
    </td>
    
  </tr>
  
</table>